name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
  id-token: write
  pages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git Credentials
        uses: actions/checkout@v5
      - name: Set up Python runtime
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache 
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material[imaging] mkdocs-awesome-nav 
      - run: mkdocs gh-deploy --force
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v4
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
